-- USERS
CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255),                -- <--- added
    balance DECIMAL(12,2) DEFAULT 0
);

-- CATEGORIES for products
CREATE TABLE Categories (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) UNIQUE NOT NULL
);

-- PRODUCTS
CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    image_url TEXT,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    category_id INT REFERENCES Categories(id),
    creator_id INT REFERENCES Users(id)   -- <--- added
);

-- INVENTORY (per-seller per-product quantities/prices)
CREATE TABLE Inventory (
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL DEFAULT 0,
    seller_price DECIMAL(12,2),
    PRIMARY KEY (seller_id, product_id)
);

-- WISHLIST
CREATE TABLE Wishes (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_added TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT wishes_uid_pid_unique UNIQUE (uid, pid)
);


-- CART ITEMS (pending order: includes seller, user, product, quantity)
DROP TABLE IF EXISTS CartItems CASCADE;
CREATE TABLE CartItems (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL DEFAULT 1,
    saved BOOLEAN NOT NULL DEFAULT FALSE,
    time_added TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (uid, pid, seller_id)
);


-- ORDERS (each checkout creates an order)
CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    status VARCHAR(50) DEFAULT 'pending',
    total_amount DECIMAL(12,2) NOT NULL
);

-- ORDER ITEMS (order details, with seller and fulfillment details for each line)
CREATE TABLE OrderItems (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- <--- added
    order_id INT NOT NULL REFERENCES Orders(id),
    product_id INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    fulfillment_status VARCHAR(50) DEFAULT 'pending',
    fulfilled_date TIMESTAMP WITHOUT TIME ZONE                 -- <--- added
);

-- PURCHASES HISTORY (for reference, not strictly needed with Orders/OrderItems)
CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- REVIEWS (per product, per user)
CREATE TABLE Reviews (
    review_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL REFERENCES Products(id),
    user_id INT NOT NULL REFERENCES Users(id),
    rating INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    date_reviewed TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT reviews_product_user_unique UNIQUE (product_id, user_id)
);


CREATE TABLE IF NOT EXISTS SellerReviews (
    id SERIAL PRIMARY KEY,
    seller_id INTEGER REFERENCES Users(id),
    user_id INTEGER REFERENCES Users(id),
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    date_reviewed TIMESTAMP DEFAULT NOW()
);
